### ISSUE TITLE
Rotation fails when file is in use

### ISSUE THREAD

**Issue by AntAgna** [plecos/logrotatewin#18]
I am trying to do log rotation on the log file generated by OpenVPN.

It fails with these error messages :
logrotate: Error renaming file C:\Program Files\OpenVPN\log\sos-vpn.log to C:\Program Files\OpenVPN\log\sos-vpn.log.1
logrotate: The process cannot access the file because it is being used by another process.
logrotate: Error in CompressRotatedFile with file C:\Program Files\OpenVPN\log\sos-vpn.log.1
logrotate: Exception: Could not find file 'C:\Program Files\OpenVPN\log\sos-vpn.log.1'.
logrotate: StackTrace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at logrotate.Program.CompressRotatedFile(String m_filepath, logrotateconf lrc)

My logrotate.conf contains this :
compress
"C:\Program Files\OpenVPN\log\sos-vpn.log" {
	rotate 5
	daily
}

Is there a way to make this work ?

**Comment by plecos** [comment]
Does it work if you don't use compression?

**Comment by AntAgna** [comment]
If I comment the compress line, it fails with the same error message.

I think the important part is : 
Error renaming file sos-vpn.log to sos-vpn.log.1
The process cannot access the file because it is being used by another process.

While the service is active, it keeps the file open so we can't rename it.
I tried other scripts that also fail for the same reason.
If I modify the scripts to copy the file and then truncate, the truncate fails for the same reason.

As a workaround, I plan to run logrotate during boot before OpenVPN has started.

**Comment by Britford** [comment]
I also get a file-in-use error when a file is locked by another process.  
   C:\Users\Ted\AppData\Local\Xamarin\Logs\15.0\*.log {
	rotate 5
	daily
   }

**Comment by loxway** [comment]
Hi, the point is that should not raise an exeption and stop the program. Should only warn an go on. In use files are easy to find.
Lorenz

**Comment by wdc596933938** [comment]
Hi, I have received a same problem. I solved this by modify the soure code and replaced "File.Move" to "File.Copy". Then truncate this file.

**Comment by bozdoz** [comment]
I am running into the same problem, and I don't know enough about C# to modify source code.

**Comment by plecos** [comment]
I have made a lot of bug fixes and updates.

Try the latest release and post again if there is still an issue:

https://github.com/plecos/logrotatewin/releases/tag/v0.0.22
